### ISSUE TITLE
执行npm run dev后项目重复循环构建

### ISSUE THREAD

**Issue by ZiuChen** [Trim21/webpack-userscript-template#229]
# Description

未知原因导致执行`npm run dev`后，项目被一次又一次的重复构建，这期间能够响应`watch`文件变化，并且终端报出不一样的日志，由此我推测可能不是`watch mode`的问题。

## Environment

- language version: `Windows 10` `Webpack 5.67.0` `Node.JS 14.16.1`

## Demonstration

我录制了一个演示视频，我给watchOptions加了5秒的aggregateTimeout，不然会刷的更快
[Video](https://v.qq.com/txp/iframe/player.html?vid=u33245pi4j1)

**Comment by Trim21** [comment]
不开vscode，用终端直接运行`npm run dev`有问题吗？

**Comment by ZiuChen** [comment]
我查阅了一些资料，尝试了很多方法，但仍然没有头绪：
[Webpack keeps rebuilding](https://github.com/nuxt/nuxt.js/issues/324)
[Infinite Loop on watch](https://github.com/laravel-mix/laravel-mix/issues/228)
[Watching Directories while ignoring some other files in the same directories.](https://github.com/webpack/webpack/issues/11570)
[Infinite rebuild loop in vagrant environment in watch mode](https://github.com/webpack/webpack/issues/12340)

**Comment by Trim21** [comment]
`AutoImport({resolvers: [ElementPlusResolver()]})` 和  `Components({ resolvers: [ElementPlusResolver()] }),` 会修改 `auto-imports.d.ts` 和 `components.d.ts` 两个文件，把这两个文件ignore或者想办法替代这个插件
