### ISSUE TITLE
压缩代码同时保留脚本元信息

### ISSUE THREAD

**Issue by ZiuChen** [Trim21/webpack-userscript-template#241]
# Description

我将`webpack.base.js`中的`minimize`选项改为了`true`，希望能压缩代码，但是代码压缩后`metadata`也被压缩了。

请问我应该如何配置，让代码压缩的同时保留脚本的`metadata`呢？

## Environment

- language version: `Webpack 5.56.0`
- app/lib/repo version: `none`

## How to reproduce

`none`

## Expectations

压缩代码的同时保留脚本的元信息

**Comment by Trim21** [comment]
https://webpack.js.org/configuration/optimization/#optimizationminimizer
