### ISSUE TITLE
How is auto deploy intended to work?

### ISSUE THREAD

**Issue by Syntoxr** [trim21/webpack-userscript-template#513]
# Description

Hi,
first of all, thanks for this great template. It really helped me creating more complex userscripts.

I am currently in the process of getting automated deploys running and it already works to the point where a packed `index.prod.user.js` file gets commited to the `preview-dist` branch.

But how is it intended to deploy to the `gh-pages` branch?
Should I just create a `v*` branch and commit to it so the `deploy` workflow gets triggered or is there another intended - automated way to do so?

Thanks for your help!

**Comment by trim21** [comment]
`preview-dist` is build from `master` branch https://github.com/trim21/webpack-userscript-template/blob/master/.github/workflows/deploy-preview.yaml#L28C27-L28C39

`gh-pages` branch is build from latest tag

**Comment by Syntoxr** [comment]
Makes sense.
Thanks for your quick response!
